[package]
name = "digital_envelope"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
rand = "0.8.5"
rsa = {version = "0.9.3",features = ["sha2"]}
serde = {version = "1.0.190", features = ["derive"]}
serde_json = "1.0.107"
sha2 = "0.10.8"
